owner: maksimus12
repo: me-upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  baseUrl: /me-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ME Upptime
  introTitle: "**ME Upptime** — мониторинг доступности моих сайтов"
  introMessage: Эта страница статуса использует данные в реальном времени из нашего [GitHub репозитория](https://github.com/maksimus12/me-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/maksimus12/me-upptime
