owner: maksimus12
repo: me-upptime

sites:
  - name: Mission Eurasia Field
    url: https://missioneurasiafield.org/
  - name: Mission in Profession (Landing)
    url: https://pro.missioneurasiafield.org/
  - name: Empower (Landing)
    url: https://empower.missioneurasiafield.org/

status-website:
  baseUrl: /me-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ME Upptime
  introTitle: "**ME Upptime** — мониторинг доступности моих сайтов"
  introMessage: Hello lets see our sites uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/maksimus12/me-upptime
